# Generated by Django 3.0.6 on 2020-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XYZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_head', models.CharField(blank=True, max_length=255, null=True)),
                ('message_body', models.TextField()),
                ('message_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('message_creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
