# Generated by Django 3.0.6 on 2020-06-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_auto_20200615_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_real_time',
            field=models.IntegerField(default=10),
        ),
    ]
